### ISSUE TITLE
Playback speed

### ISSUE THREAD

**Issue by popeen** [popeen/Booksonic-LegacyServer#4]
Look in to changing the playback speed on the server. This will be good for when using web gui or a third party client that does not support playback speed

**Comment by madamiub** [comment]
I tried your app out on February 3rd but since it doesn't have playback speed adjustment, I decided it wasn't worth it. I still have my subsonic server set up, though. Do you think this will be possible and will or require using booksonic as the server?

**Comment by popeen** [comment]
Sad to hear but I can understand you completely, I have never changed
playback speed on audiobooks but for most podcasts it's a must for me.

If you are just interested in changing the playback speed on the phone it
should be possible to implement in the app without requireing the Booksonic
server yes. As to when it will happen I'm afraid I have no idea as I
haven't really looked in to that part of the code yet so I have no idea how
hard it would be to implement, hopefully it shouldn't take to long and it
is on the top of the list.

Adding the feature to the server is for people wanting to use third party
apps or the web GUI.

**Comment by madamiub** [comment]
Thanks for the quick reply and all your work on the project. If you don't mind updating this thread if you do eventually get to it, I'd love to try booksonic again.

**Comment by popeen** [comment]
Yeah, sure. I'll try and remember to post a comment here once it's added.

**Comment by popeen** [comment]
The app has this for a long time by now, and https://github.com/popeen/Booksonic-Air will have it at release
