### ISSUE TITLE
Scan doesn't reliably detect new files

### ISSUE THREAD

**Issue by IronicBadger** [popeen/Booksonic-LegacyServer#43]
Recently added a new audiobook to the 300+ I already have. Using the linuxserver container I have set the PUID and PGID to correct values (verified using a `docker exec` into the container and checking read / write permissions of the `abc` user).

No matter what permission I give the new books files, it isn't detected. Not even with a `chmod -R 777`. Any ideas? The logs show nothing useful even in debug.

**Comment by keaganhilliard** [comment]
I am running into the same issues. I found that dropping the config folder and recreating the library allowed the new books to be scanned in with the initial library import... Definitely not ideal

**Comment by IronicBadger** [comment]
Looks like this is stale.

**Comment by popeen** [comment]
Would you mind checking if you can replicate the problem on https://github.com/popeen/Booksonic-Air and if so open a ticket there? I plan on doing more server updates on Air then I did on this one so if it's still there I will look in to it.

**Comment by IronicBadger** [comment]
Sure, I haven't migrated yet (waiting for a linuxserver.io docker update)

**Comment by popeen** [comment]
Sounds great, should be sometime in mid September if they do the update immediately on release, will make sure to ping them about it once released.
