### ISSUE TITLE
Compiling not possible and a lot of java errors

### ISSUE THREAD

**Issue by Friday13th87** [popeen/Booksonic-LegacyServer#53]
i am getting a "Subsonic REST API" failure when compiling the source
`File [/Popeens-Subsonic/subsonic-rest-api/src/main/resources/subsonic-rest-api.xsd] was changed since the last build.
File [/Popeens-Subsonic/subsonic-rest-api/pom.xml] was changed since the last build.
 Checking up-to-date depends [[/Popeens-Subsonic/subsonic-rest-api/src/main/resources/subsonic-rest-api.xsd, /Popeens-Subsonic/subsonic-rest-api/pom.xml]].
Checking up-to-date produces [[]].
Depends timestamp [1.583.344.589.686], produces timestamp [null].`

and i found a lot of errors while looking through the code actually.
the KakaduaUtil.java is 2 times in the sourcs, in
`Popeens-Subsonic/subsonic-main/src/main/java/net/sourceforge/subsonic/util`
and in
`Popeens-Subsonic/subsonic-main/src/main/java/net/kakadua`
in the net/kakadua/KakaduaUtil.java there is 
`public static String http_get_contents`
defined 2 times at line 91 and line 50 and a lot of missing spaces before and after "{" and "}"

i tried to implement correct reading of authors desc.txt and cover.jpg as the code is missing at ArtistDao.java

but i would need to make the source working before i cann add those features.

do u have a running source code version and could u update it to the recent version?

[logs.txt](https://github.com/popeen/Popeens-Subsonic/files/4289951/logs.txt)

**Comment by popeen** [comment]
please use popeen/Booksonic-Air instead
